-- CSAF Analytics Phase 0
-- Canonical, staging and audit tables for manual CSV exchange.
-- Oracle Database 19c compatible. Run once in the APEX parsing schema.

prompt Creating CSAF Phase 0 tables

create table csaf_advisories (
  advisory_id         number generated by default on null as identity,
  vendor              varchar2(64) not null,
  advisory_reference  varchar2(128) not null,
  revision            varchar2(64) not null,
  published_date      date,
  revised_date        date,
  tlp                 varchar2(16),
  source_filename     varchar2(512),
  source_url          varchar2(2000),
  source_hash         varchar2(64) not null,
  loaded_at           timestamp with time zone default systimestamp not null,
  constraint pk_csaf_advisories primary key (advisory_id),
  constraint uk_csaf_advisory_revision
    unique (vendor, advisory_reference, revision),
  constraint ck_csaf_advisory_hash check (length(source_hash) = 64)
);

create index idx_csaf_advisory_hash on csaf_advisories (source_hash);

create table csaf_products (
  product_id          varchar2(500) not null,
  family              varchar2(250),
  product_name        varchar2(500),
  product_version     varchar2(200),
  cpe                 varchar2(1000),
  first_seen          date,
  last_seen           date,
  created_at          timestamp with time zone default systimestamp not null,
  updated_at          timestamp with time zone default systimestamp not null,
  constraint pk_csaf_products primary key (product_id)
);

create table csaf_vulnerabilities (
  cve                 varchar2(30) not null,
  cve_year            number,
  description         clob,
  first_advisory_id   number,
  created_at          timestamp with time zone default systimestamp not null,
  updated_at          timestamp with time zone default systimestamp not null,
  constraint pk_csaf_vulnerabilities primary key (cve),
  constraint fk_csaf_vuln_first_advisory foreign key (first_advisory_id)
    references csaf_advisories (advisory_id)
);

create table csaf_facts (
  advisory_id         number not null,
  cve                 varchar2(30) not null,
  product_id          varchar2(500) not null,
  status              varchar2(40) not null,
  vex_justification   varchar2(100),
  cvss_score          number(4,1),
  cvss_vector         varchar2(200),
  av                  varchar2(2),
  pr                  varchar2(2),
  ui                  varchar2(2),
  scope_value         varchar2(2),
  confidentiality     varchar2(2),
  integrity_value     varchar2(2),
  availability_value  varchar2(2),
  pre_auth            number(1),
  scope_changed       number(1),
  high_impact         number(1),
  fix_url             varchar2(2000),
  fix_note            varchar2(100),
  fix_category        varchar2(50),
  vendor_bug_id       varchar2(100),
  created_at          timestamp with time zone default systimestamp not null,
  constraint pk_csaf_facts primary key (advisory_id, cve, product_id),
  constraint fk_csaf_fact_advisory foreign key (advisory_id)
    references csaf_advisories (advisory_id),
  constraint fk_csaf_fact_vulnerability foreign key (cve)
    references csaf_vulnerabilities (cve),
  constraint fk_csaf_fact_product foreign key (product_id)
    references csaf_products (product_id),
  constraint ck_csaf_fact_pre_auth check (pre_auth in (0, 1)),
  constraint ck_csaf_fact_scope check (scope_changed in (0, 1)),
  constraint ck_csaf_fact_impact check (high_impact in (0, 1))
);

create index idx_csaf_facts_cve on csaf_facts (cve);
create index idx_csaf_facts_product on csaf_facts (product_id);

create table csaf_enrichment (
  cve                 varchar2(30) not null,
  observed_date       date not null,
  epss                number(10,9),
  epss_percentile     number(10,9),
  kev                 number(1),
  kev_added           date,
  kev_due             date,
  kev_ransomware      varchar2(30),
  public_exploits     number,
  exploit_url         varchar2(2000),
  epss_status         varchar2(16) not null,
  kev_status          varchar2(16) not null,
  exploit_status      varchar2(16) not null,
  imported_at         timestamp with time zone default systimestamp not null,
  last_batch_id       varchar2(200) not null,
  constraint pk_csaf_enrichment primary key (cve, observed_date),
  constraint fk_csaf_enrichment_cve foreign key (cve)
    references csaf_vulnerabilities (cve),
  constraint ck_csaf_enrichment_kev check (kev in (0, 1)),
  constraint ck_csaf_epss_status check
    (epss_status in ('success', 'unavailable', 'error')),
  constraint ck_csaf_kev_status check
    (kev_status in ('success', 'unavailable', 'error')),
  constraint ck_csaf_exploit_status check
    (exploit_status in ('success', 'unavailable', 'error'))
);

create index idx_csaf_enrichment_date
  on csaf_enrichment (observed_date desc);

create table csaf_load_log (
  load_id             number generated by default on null as identity,
  batch_id            varchar2(200) not null,
  load_type           varchar2(32) not null,
  source              varchar2(512),
  source_hash         varchar2(64),
  started_at          timestamp with time zone default systimestamp not null,
  finished_at         timestamp with time zone,
  status              varchar2(16) not null,
  rows_affected       number default 0 not null,
  message             varchar2(2000),
  constraint pk_csaf_load_log primary key (load_id),
  constraint ck_csaf_load_type check
    (load_type in ('advisory', 'enrichment')),
  constraint ck_csaf_load_status check
    (status in ('success', 'partial', 'failed', 'skipped', 'conflict'))
);

create index idx_csaf_load_batch on csaf_load_log (batch_id, load_type);

-- Data Workshop loads these columns as text. Promotion performs conversion.
create table csaf_finding_stage (
  stage_id             number generated by default on null as identity,
  batch_id             varchar2(200) not null,
  vendor               varchar2(64),
  advisory_reference   varchar2(128),
  advisory_revision    varchar2(64),
  source_hash           varchar2(64),
  source_filename       varchar2(512),
  source_url            varchar2(2000),
  published_date        varchar2(30),
  revised_date          varchar2(30),
  tlp                   varchar2(16),
  cve                   varchar2(30),
  description           clob,
  product_id            varchar2(500),
  product_family        varchar2(250),
  product_name          varchar2(500),
  product_version       varchar2(200),
  cpe                   varchar2(1000),
  status                varchar2(40),
  vex_justification     varchar2(100),
  cvss_score            varchar2(30),
  cvss_vector           varchar2(200),
  av                    varchar2(2),
  pr                    varchar2(2),
  ui                    varchar2(2),
  scope_value           varchar2(2),
  confidentiality       varchar2(2),
  integrity             varchar2(2),
  availability          varchar2(2),
  pre_auth              varchar2(1),
  scope_changed         varchar2(1),
  high_impact           varchar2(1),
  fix_url               varchar2(2000),
  fix_note              varchar2(100),
  fix_category          varchar2(50),
  vendor_bug_id         varchar2(100),
  staged_at             timestamp with time zone default systimestamp not null,
  constraint pk_csaf_finding_stage primary key (stage_id)
);

create index idx_csaf_finding_stage_batch
  on csaf_finding_stage (batch_id);

create table csaf_enrichment_stage (
  stage_id             number generated by default on null as identity,
  batch_id             varchar2(200) not null,
  cve                  varchar2(30),
  observed_date        varchar2(30),
  epss                 varchar2(30),
  epss_percentile      varchar2(30),
  kev                  varchar2(1),
  kev_added            varchar2(30),
  kev_due              varchar2(30),
  kev_ransomware       varchar2(30),
  public_exploits      varchar2(30),
  exploit_url          varchar2(2000),
  epss_status          varchar2(16),
  kev_status           varchar2(16),
  exploit_status       varchar2(16),
  staged_at            timestamp with time zone default systimestamp not null,
  constraint pk_csaf_enrichment_stage primary key (stage_id)
);

create index idx_csaf_enrichment_stage_batch
  on csaf_enrichment_stage (batch_id);

create or replace view csaf_latest_enrichment_v as
select cve,
       observed_date,
       epss,
       epss_percentile,
       kev,
       kev_added,
       kev_due,
       kev_ransomware,
       public_exploits,
       exploit_url,
       epss_status,
       kev_status,
       exploit_status,
       imported_at,
       last_batch_id
  from (
    select e.*,
           row_number() over (
             partition by e.cve
             order by e.observed_date desc, e.imported_at desc
           ) as rn
      from csaf_enrichment e
  )
 where rn = 1;

prompt CSAF Phase 0 schema complete
