-- sed-dashboard MVP
-- Script 02: Lookup Tables
--
-- Purpose:
--   Create lookup/reference tables and seed initial lookup values.
--
-- Run after:
--   01_drop_objects.sql, only if resetting schema.
--
-- Run before:
--   03_core_tables.sql

prompt Script 02 - Lookup Tables

create table customer_tiers (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_customer_tiers primary key (lookup_id),
  constraint uk_customer_tiers_code unique (lookup_code),
  constraint ck_customer_tiers_active check (active_flag in ('Y','N'))
);

create table customer_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_customer_statuses primary key (lookup_id),
  constraint uk_customer_statuses_code unique (lookup_code),
  constraint ck_customer_statuses_active check (active_flag in ('Y','N'))
);

create table team_roles (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_team_roles primary key (lookup_id),
  constraint uk_team_roles_code unique (lookup_code),
  constraint ck_team_roles_active check (active_flag in ('Y','N'))
);

create table health_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_health_statuses primary key (lookup_id),
  constraint uk_health_statuses_code unique (lookup_code),
  constraint ck_health_statuses_active check (active_flag in ('Y','N'))
);

create table interaction_types (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_interaction_types primary key (lookup_id),
  constraint uk_interaction_types_code unique (lookup_code),
  constraint ck_interaction_types_active check (active_flag in ('Y','N'))
);

create table review_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_review_statuses primary key (lookup_id),
  constraint uk_review_statuses_code unique (lookup_code),
  constraint ck_review_statuses_active check (active_flag in ('Y','N'))
);

create table action_priorities (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_action_priorities primary key (lookup_id),
  constraint uk_action_priorities_code unique (lookup_code),
  constraint ck_action_priorities_active check (active_flag in ('Y','N'))
);

create table action_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_action_statuses primary key (lookup_id),
  constraint uk_action_statuses_code unique (lookup_code),
  constraint ck_action_statuses_active check (active_flag in ('Y','N'))
);

create table severity_levels (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_severity_levels primary key (lookup_id),
  constraint uk_severity_levels_code unique (lookup_code),
  constraint ck_severity_levels_active check (active_flag in ('Y','N'))
);

create table security_case_types (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_security_case_types primary key (lookup_id),
  constraint uk_security_case_types_code unique (lookup_code),
  constraint ck_security_case_types_active check (active_flag in ('Y','N'))
);

create table security_case_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_security_case_statuses primary key (lookup_id),
  constraint uk_security_case_statuses_code unique (lookup_code),
  constraint ck_security_case_statuses_active check (active_flag in ('Y','N'))
);

create table security_impact_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_security_impact_statuses primary key (lookup_id),
  constraint uk_security_impact_statuses_code unique (lookup_code),
  constraint ck_security_impact_statuses_active check (active_flag in ('Y','N'))
);

create table security_impact_confidence_levels (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_security_impact_conf_levels primary key (lookup_id),
  constraint uk_security_impact_conf_levels unique (lookup_code),
  constraint ck_security_impact_conf_active check (active_flag in ('Y','N'))
);

create table remediation_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_remediation_statuses primary key (lookup_id),
  constraint uk_remediation_statuses_code unique (lookup_code),
  constraint ck_remediation_statuses_active check (active_flag in ('Y','N'))
);

create table security_event_types (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_security_event_types primary key (lookup_id),
  constraint uk_security_event_types_code unique (lookup_code),
  constraint ck_security_event_types_active check (active_flag in ('Y','N'))
);

create table security_event_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_security_event_statuses primary key (lookup_id),
  constraint uk_security_event_statuses_code unique (lookup_code),
  constraint ck_security_event_statuses_active check (active_flag in ('Y','N'))
);

create table notification_campaign_types (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_notification_campaign_types primary key (lookup_id),
  constraint uk_notification_campaign_types unique (lookup_code),
  constraint ck_notification_campaign_types check (active_flag in ('Y','N'))
);

create table notification_campaign_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_notification_campaign_status primary key (lookup_id),
  constraint uk_notification_campaign_status unique (lookup_code),
  constraint ck_notification_campaign_status check (active_flag in ('Y','N'))
);

create table notification_recipient_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_notification_recipient_status primary key (lookup_id),
  constraint uk_notification_recipient_status unique (lookup_code),
  constraint ck_notification_recipient_status check (active_flag in ('Y','N'))
);

create table alert_types (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_alert_types primary key (lookup_id),
  constraint uk_alert_types_code unique (lookup_code),
  constraint ck_alert_types_active check (active_flag in ('Y','N'))
);

create table alert_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_alert_statuses primary key (lookup_id),
  constraint uk_alert_statuses_code unique (lookup_code),
  constraint ck_alert_statuses_active check (active_flag in ('Y','N'))
);

create table estate_types (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_estate_types primary key (lookup_id),
  constraint uk_estate_types_code unique (lookup_code),
  constraint ck_estate_types_active check (active_flag in ('Y','N'))
);

create table estate_lifecycle_statuses (
  lookup_id number generated by default on null as identity,
  lookup_code varchar2(50) not null,
  lookup_name varchar2(200) not null,
  display_order number,
  active_flag varchar2(1) default 'Y' not null,
  created_at timestamp default systimestamp not null,
  constraint pk_estate_lifecycle_statuses primary key (lookup_id),
  constraint uk_estate_lifecycle_statuses unique (lookup_code),
  constraint ck_estate_lifecycle_statuses check (active_flag in ('Y','N'))
);

insert into customer_tiers (lookup_code, lookup_name, display_order) values ('TIER_1', 'Tier 1 - Strategic', 10);
insert into customer_tiers (lookup_code, lookup_name, display_order) values ('TIER_2', 'Tier 2 - Enterprise', 20);
insert into customer_tiers (lookup_code, lookup_name, display_order) values ('TIER_3', 'Tier 3 - Growth', 30);
insert into customer_tiers (lookup_code, lookup_name, display_order) values ('TIER_4', 'Tier 4 - Digital', 40);

insert into customer_statuses (lookup_code, lookup_name, display_order) values ('ACTIVE', 'Active', 10);
insert into customer_statuses (lookup_code, lookup_name, display_order) values ('INACTIVE', 'Inactive', 20);
insert into customer_statuses (lookup_code, lookup_name, display_order) values ('PROSPECT', 'Prospect', 30);

insert into team_roles (lookup_code, lookup_name, display_order) values ('PRIMARY_SECURITY_ADVISOR', 'Primary Security Advisor', 10);
insert into team_roles (lookup_code, lookup_name, display_order) values ('CSS_SALES_REP', 'CSS Sales Representative', 20);
insert into team_roles (lookup_code, lookup_name, display_order) values ('CUSTOMER_SUCCESS_MANAGER', 'Customer Success Manager', 30);
insert into team_roles (lookup_code, lookup_name, display_order) values ('SOLUTION_ARCHITECT', 'Solution Architect', 40);
insert into team_roles (lookup_code, lookup_name, display_order) values ('EXECUTIVE_SPONSOR', 'Executive Sponsor', 50);
insert into team_roles (lookup_code, lookup_name, display_order) values ('OTHER', 'Other', 90);

insert into health_statuses (lookup_code, lookup_name, display_order) values ('GOOD', 'Good', 10);
insert into health_statuses (lookup_code, lookup_name, display_order) values ('AT_RISK', 'At Risk', 20);
insert into health_statuses (lookup_code, lookup_name, display_order) values ('NEEDS_ATTENTION', 'Needs Attention', 30);

insert into interaction_types (lookup_code, lookup_name, display_order) values ('MEETING', 'Meeting', 10);
insert into interaction_types (lookup_code, lookup_name, display_order) values ('CALL', 'Call', 20);
insert into interaction_types (lookup_code, lookup_name, display_order) values ('EMAIL', 'Email', 30);
insert into interaction_types (lookup_code, lookup_name, display_order) values ('WORKSHOP', 'Workshop', 40);
insert into interaction_types (lookup_code, lookup_name, display_order) values ('BRIEFING', 'Briefing', 50);

insert into review_statuses (lookup_code, lookup_name, display_order) values ('SCHEDULED', 'Scheduled', 10);
insert into review_statuses (lookup_code, lookup_name, display_order) values ('COMPLETED', 'Completed', 20);
insert into review_statuses (lookup_code, lookup_name, display_order) values ('OVERDUE', 'Overdue', 30);
insert into review_statuses (lookup_code, lookup_name, display_order) values ('CANCELLED', 'Cancelled', 40);

insert into action_priorities (lookup_code, lookup_name, display_order) values ('LOW', 'Low', 10);
insert into action_priorities (lookup_code, lookup_name, display_order) values ('MEDIUM', 'Medium', 20);
insert into action_priorities (lookup_code, lookup_name, display_order) values ('HIGH', 'High', 30);
insert into action_priorities (lookup_code, lookup_name, display_order) values ('CRITICAL', 'Critical', 40);

insert into action_statuses (lookup_code, lookup_name, display_order) values ('OPEN', 'Open', 10);
insert into action_statuses (lookup_code, lookup_name, display_order) values ('IN_PROGRESS', 'In Progress', 20);
insert into action_statuses (lookup_code, lookup_name, display_order) values ('BLOCKED', 'Blocked', 30);
insert into action_statuses (lookup_code, lookup_name, display_order) values ('COMPLETED', 'Completed', 40);
insert into action_statuses (lookup_code, lookup_name, display_order) values ('CANCELLED', 'Cancelled', 50);

insert into severity_levels (lookup_code, lookup_name, display_order) values ('LOW', 'Low', 10);
insert into severity_levels (lookup_code, lookup_name, display_order) values ('MEDIUM', 'Medium', 20);
insert into severity_levels (lookup_code, lookup_name, display_order) values ('HIGH', 'High', 30);
insert into severity_levels (lookup_code, lookup_name, display_order) values ('CRITICAL', 'Critical', 40);

insert into security_case_types (lookup_code, lookup_name, display_order) values ('CVE_ADVISORY', 'CVE Advisory', 10);
insert into security_case_types (lookup_code, lookup_name, display_order) values ('CPU', 'Critical Patch Update', 20);
insert into security_case_types (lookup_code, lookup_name, display_order) values ('SECURITY_ALERT', 'Security Alert', 30);
insert into security_case_types (lookup_code, lookup_name, display_order) values ('PRODUCT_ADVISORY', 'Product Advisory', 40);

insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('DRAFT', 'Draft', 10);
insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('ACTIVE', 'Active', 20);
insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('ASSESSING', 'Assessing Impact', 30);
insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('CAMPAIGN_ACTIVE', 'Campaign Active', 40);
insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('MONITORING', 'Monitoring', 50);
insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('CLOSED', 'Closed', 60);
insert into security_case_statuses (lookup_code, lookup_name, display_order) values ('CANCELLED', 'Cancelled', 70);

insert into security_impact_statuses (lookup_code, lookup_name, display_order) values ('UNKNOWN', 'Unknown', 10);
insert into security_impact_statuses (lookup_code, lookup_name, display_order) values ('POTENTIALLY_IMPACTED', 'Potentially Impacted', 20);
insert into security_impact_statuses (lookup_code, lookup_name, display_order) values ('CONFIRMED_IMPACTED', 'Confirmed Impacted', 30);
insert into security_impact_statuses (lookup_code, lookup_name, display_order) values ('NOT_IMPACTED', 'Not Impacted', 40);
insert into security_impact_statuses (lookup_code, lookup_name, display_order) values ('REMEDIATED', 'Remediated', 50);

insert into security_impact_confidence_levels (lookup_code, lookup_name, display_order) values ('LOW', 'Low', 10);
insert into security_impact_confidence_levels (lookup_code, lookup_name, display_order) values ('MEDIUM', 'Medium', 20);
insert into security_impact_confidence_levels (lookup_code, lookup_name, display_order) values ('HIGH', 'High', 30);
insert into security_impact_confidence_levels (lookup_code, lookup_name, display_order) values ('CONFIRMED', 'Confirmed', 40);

insert into remediation_statuses (lookup_code, lookup_name, display_order) values ('NOT_STARTED', 'Not Started', 10);
insert into remediation_statuses (lookup_code, lookup_name, display_order) values ('IN_PROGRESS', 'In Progress', 20);
insert into remediation_statuses (lookup_code, lookup_name, display_order) values ('REMEDIATED', 'Remediated', 30);
insert into remediation_statuses (lookup_code, lookup_name, display_order) values ('NOT_REQUIRED', 'Not Required', 40);

insert into security_event_types (lookup_code, lookup_name, display_order) values ('CVE', 'CVE', 10);
insert into security_event_types (lookup_code, lookup_name, display_order) values ('CPU', 'Critical Patch Update', 20);
insert into security_event_types (lookup_code, lookup_name, display_order) values ('SECURITY_ALERT', 'Security Alert', 30);
insert into security_event_types (lookup_code, lookup_name, display_order) values ('VULNERABILITY_ADVISORY', 'Vulnerability Advisory', 40);

insert into security_event_statuses (lookup_code, lookup_name, display_order) values ('DRAFT', 'Draft', 10);
insert into security_event_statuses (lookup_code, lookup_name, display_order) values ('ACTIVE', 'Active', 20);
insert into security_event_statuses (lookup_code, lookup_name, display_order) values ('SUPERSEDED', 'Superseded', 30);
insert into security_event_statuses (lookup_code, lookup_name, display_order) values ('CLOSED', 'Closed', 40);

insert into notification_campaign_types (lookup_code, lookup_name, display_order) values ('CRITICAL_CVE', 'Critical CVE Notification', 10);
insert into notification_campaign_types (lookup_code, lookup_name, display_order) values ('CPU', 'Critical Patch Update Notification', 20);
insert into notification_campaign_types (lookup_code, lookup_name, display_order) values ('SECURITY_ALERT', 'Security Alert Notification', 30);

insert into notification_campaign_statuses (lookup_code, lookup_name, display_order) values ('DRAFT', 'Draft', 10);
insert into notification_campaign_statuses (lookup_code, lookup_name, display_order) values ('READY_FOR_REVIEW', 'Ready for Review', 20);
insert into notification_campaign_statuses (lookup_code, lookup_name, display_order) values ('APPROVED', 'Approved', 30);
insert into notification_campaign_statuses (lookup_code, lookup_name, display_order) values ('IN_PROGRESS', 'In Progress', 40);
insert into notification_campaign_statuses (lookup_code, lookup_name, display_order) values ('COMPLETED', 'Completed', 50);
insert into notification_campaign_statuses (lookup_code, lookup_name, display_order) values ('CANCELLED', 'Cancelled', 60);

insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('PENDING', 'Pending', 10);
insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('READY', 'Ready', 20);
insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('SENT', 'Sent', 30);
insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('ACKNOWLEDGED', 'Acknowledged', 40);
insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('FOLLOW_UP_REQUIRED', 'Follow-up Required', 50);
insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('NOT_APPLICABLE', 'Not Applicable', 60);
insert into notification_recipient_statuses (lookup_code, lookup_name, display_order) values ('FAILED_BLOCKED', 'Failed or Blocked', 70);

insert into alert_types (lookup_code, lookup_name, display_order) values ('NO_INTERACTION_90_DAYS', 'No Interaction in 90 Days', 10);
insert into alert_types (lookup_code, lookup_name, display_order) values ('REVIEW_OVERDUE', 'Review Overdue', 20);
insert into alert_types (lookup_code, lookup_name, display_order) values ('ACTION_OVERDUE', 'Action Overdue', 30);
insert into alert_types (lookup_code, lookup_name, display_order) values ('SECURITY_CASE_IMPACT', 'Security Case Impact', 40);
insert into alert_types (lookup_code, lookup_name, display_order) values ('CAMPAIGN_FOLLOW_UP', 'Campaign Follow-up Required', 50);
insert into alert_types (lookup_code, lookup_name, display_order) values ('HEALTH_NEEDS_ATTENTION', 'Health Needs Attention', 60);

insert into alert_statuses (lookup_code, lookup_name, display_order) values ('NEW', 'New', 10);
insert into alert_statuses (lookup_code, lookup_name, display_order) values ('ACKNOWLEDGED', 'Acknowledged', 20);
insert into alert_statuses (lookup_code, lookup_name, display_order) values ('IN_PROGRESS', 'In Progress', 30);
insert into alert_statuses (lookup_code, lookup_name, display_order) values ('RESOLVED', 'Resolved', 40);
insert into alert_statuses (lookup_code, lookup_name, display_order) values ('DISMISSED', 'Dismissed', 50);

insert into estate_types (lookup_code, lookup_name, display_order) values ('PRODUCT', 'Product', 10);
insert into estate_types (lookup_code, lookup_name, display_order) values ('SERVICE', 'Service', 20);
insert into estate_types (lookup_code, lookup_name, display_order) values ('WORKLOAD', 'Workload', 30);
insert into estate_types (lookup_code, lookup_name, display_order) values ('ENVIRONMENT', 'Environment', 40);

insert into estate_lifecycle_statuses (lookup_code, lookup_name, display_order) values ('ACTIVE', 'Active', 10);
insert into estate_lifecycle_statuses (lookup_code, lookup_name, display_order) values ('PLANNED', 'Planned', 20);
insert into estate_lifecycle_statuses (lookup_code, lookup_name, display_order) values ('DECOMMISSIONED', 'Decommissioned', 30);
insert into estate_lifecycle_statuses (lookup_code, lookup_name, display_order) values ('UNKNOWN', 'Unknown', 40);

commit;
