-- sed-dashboard MVP
-- Script 03: Core Tables
--
-- Purpose:
--   Create customers, users, contacts, Oracle account team, estate,
--   interactions, reviews, and actions.
--
-- Run after:
--   02_lookup_tables.sql
--
-- Run before:
--   04_security_campaign_tables.sql

prompt Script 03 - Core Tables

create table internal_users (
  user_id number generated by default on null as identity,
  full_name varchar2(200) not null,
  email varchar2(320) not null,
  role_name varchar2(100),
  department varchar2(200),
  active_flag varchar2(1) default 'Y' not null,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_internal_users primary key (user_id),
  constraint uk_internal_users_email unique (email),
  constraint ck_internal_users_active check (active_flag in ('Y','N'))
);

create table customers (
  customer_id number generated by default on null as identity,
  customer_name varchar2(300) not null,
  industry varchar2(200),
  region varchar2(100),
  tier_id number not null,
  status_id number not null,
  primary_security_advisor_user_id number not null,
  current_security_contact_id number,
  current_health_status_id number,
  current_health_score number(3),
  secalert boolean default false not null,
  health_score_reason varchar2(1000),
  health_calculated_at timestamp,
  manual_health_override_flag varchar2(1) default 'N' not null,
  health_override_reason varchar2(1000),
  health_override_by number,
  health_override_at timestamp,
  notes clob,
  source_system varchar2(100),
  source_reference varchar2(500),
  last_synced_at timestamp,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  arr number,
  registryid varchar2(128 char),
  country varchar2(128 char),
  css_services varchar2(128),
  constraint pk_customers primary key (customer_id),
  constraint uk_customers_registryid unique (registryid),
  constraint fk_customers_tier foreign key (tier_id) references customer_tiers (lookup_id),
  constraint fk_customers_status foreign key (status_id) references customer_statuses (lookup_id),
  constraint fk_customers_primary_sa foreign key (primary_security_advisor_user_id) references internal_users (user_id),
  constraint fk_customers_health_status foreign key (current_health_status_id) references health_statuses (lookup_id),
  constraint fk_customers_health_override_by foreign key (health_override_by) references internal_users (user_id),
  constraint ck_customers_health_score check (current_health_score between 0 and 100),
  constraint ck_customers_manual_override check (manual_health_override_flag in ('Y','N'))
);

create table customer_contacts (
  contact_id number generated by default on null as identity,
  customer_id number not null,
  full_name varchar2(200) not null,
  job_title varchar2(200),
  role_type varchar2(100),
  email varchar2(320),
  phone varchar2(100),
  is_primary varchar2(1) default 'N' not null,
  is_current_security_contact varchar2(1) default 'N' not null,
  active_flag varchar2(1) default 'Y' not null,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_customer_contacts primary key (contact_id),
  constraint fk_customer_contacts_customer foreign key (customer_id) references customers (customer_id),
  constraint ck_customer_contacts_primary check (is_primary in ('Y','N')),
  constraint ck_customer_contacts_current check (is_current_security_contact in ('Y','N')),
  constraint ck_customer_contacts_active check (active_flag in ('Y','N'))
);

create table oracle_account_team_members (
  account_team_member_id number generated by default on null as identity,
  customer_id number not null,
  user_id number not null,
  team_role_id number not null,
  primary_flag varchar2(1) default 'N' not null,
  start_date date default sysdate not null,
  end_date date,
  active_flag varchar2(1) default 'Y' not null,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_oracle_account_team_members primary key (account_team_member_id),
  constraint fk_oatm_customer foreign key (customer_id) references customers (customer_id),
  constraint fk_oatm_user foreign key (user_id) references internal_users (user_id),
  constraint fk_oatm_team_role foreign key (team_role_id) references team_roles (lookup_id),
  constraint ck_oatm_primary check (primary_flag in ('Y','N')),
  constraint ck_oatm_active check (active_flag in ('Y','N')),
  constraint ck_oatm_dates check (end_date is null or end_date >= start_date)
);

create table customer_estate_items (
  estate_item_id number generated by default on null as identity,
  customer_id number not null,
  estate_type_id number not null,
  product_or_service_name varchar2(300) not null,
  product_version varchar2(100),
  deployment_type varchar2(100),
  environment_name varchar2(200),
  region_name varchar2(100),
  business_criticality varchar2(50),
  security_relevance varchar2(50),
  lifecycle_status_id number,
  notes clob,
  source_system varchar2(100),
  source_reference varchar2(500),
  last_verified_at timestamp,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_customer_estate_items primary key (estate_item_id),
  constraint fk_estate_customer foreign key (customer_id) references customers (customer_id),
  constraint fk_estate_type foreign key (estate_type_id) references estate_types (lookup_id),
  constraint fk_estate_lifecycle foreign key (lifecycle_status_id) references estate_lifecycle_statuses (lookup_id)
);

create table interactions (
  interaction_id number generated by default on null as identity,
  customer_id number not null,
  interaction_type_id number not null,
  interaction_date date not null,
  subject varchar2(300) not null,
  summary clob,
  owner_user_id number,
  external_contact_id number,
  next_steps clob,
  source_system varchar2(100),
  source_reference varchar2(500),
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_interactions primary key (interaction_id),
  constraint fk_interactions_customer foreign key (customer_id) references customers (customer_id),
  constraint fk_interactions_type foreign key (interaction_type_id) references interaction_types (lookup_id),
  constraint fk_interactions_owner foreign key (owner_user_id) references internal_users (user_id),
  constraint fk_interactions_contact foreign key (external_contact_id) references customer_contacts (contact_id)
);

create table reviews (
  review_id number generated by default on null as identity,
  customer_id number not null,
  review_type varchar2(100),
  review_date date not null,
  status_id number not null,
  owner_user_id number,
  agenda clob,
  notes clob,
  outcome clob,
  completed_at timestamp,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_reviews primary key (review_id),
  constraint fk_reviews_customer foreign key (customer_id) references customers (customer_id),
  constraint fk_reviews_status foreign key (status_id) references review_statuses (lookup_id),
  constraint fk_reviews_owner foreign key (owner_user_id) references internal_users (user_id)
);

create table actions (
  action_id number generated by default on null as identity,
  customer_id number not null,
  security_case_id number,
  campaign_recipient_id number,
  title varchar2(300) not null,
  description clob,
  owner_user_id number,
  priority_id number not null,
  status_id number not null,
  due_date date,
  completed_at timestamp,
  resolution_notes clob,
  created_by varchar2(255),
  created_at timestamp default systimestamp not null,
  updated_by varchar2(255),
  updated_at timestamp,
  constraint pk_actions primary key (action_id),
  constraint fk_actions_customer foreign key (customer_id) references customers (customer_id),
  constraint fk_actions_owner foreign key (owner_user_id) references internal_users (user_id),
  constraint fk_actions_priority foreign key (priority_id) references action_priorities (lookup_id),
  constraint fk_actions_status foreign key (status_id) references action_statuses (lookup_id)
);
