-- sed-dashboard MVP
-- Script 13: Oracle Security Publications
--
-- Purpose:
--   Store Oracle CPU, CSPU, and Security Alert publications discovered from
--   the Oracle Security RSS feed. The table supports initial baseline loading
--   and subsequent NEW, UPDATED, and unchanged-publication detection.
--
-- Source:
--   https://www.oracle.com/ocom/groups/public/@otn/documents/webcontent/rss-otn-sec.xml
--
-- Run after:
--   This table has no dependency on the other application tables.
--
-- Rerun behavior:
--   This script is intended for a first-time installation. It does not drop
--   or replace an existing SECURITY_PUBLICATIONS table.

prompt Script 13 - Oracle Security Publications

create table security_publications (
  publication_id number generated by default on null as identity,
  source_code varchar2(30) default 'ORACLE_RSS' not null,
  external_id varchar2(200) not null,
  publication_type varchar2(30) not null,
  title varchar2(1000) not null,
  advisory_url varchar2(2000) not null,
  published_on date not null,
  source_pub_date varchar2(200),
  alert_state varchar2(20) not null,
  first_seen_at timestamp with time zone default systimestamp not null,
  last_seen_at timestamp with time zone default systimestamp not null,
  last_changed_at timestamp with time zone default systimestamp not null,
  created_at timestamp with time zone default systimestamp not null,
  updated_at timestamp with time zone default systimestamp not null,
  constraint pk_security_publications primary key (publication_id),
  constraint uk_security_publications unique (source_code, external_id),
  constraint ck_security_publication_type check (
    publication_type in ('CPU', 'CSPU', 'SECURITY_ALERT')
  ),
  constraint ck_security_publication_state check (
    alert_state in ('CURRENT', 'NEW', 'UPDATED')
  )
);

create index idx_security_pub_date
  on security_publications (published_on desc);

create index idx_security_pub_state
  on security_publications (alert_state, last_changed_at desc);

comment on table security_publications is
  'Oracle CPU, CSPU, and Security Alert publications discovered from the Oracle Security RSS feed';

comment on column security_publications.source_code is
  'Configured publication source; ORACLE_RSS for the Oracle Security RSS feed';

comment on column security_publications.external_id is
  'Stable external publication identifier taken from the RSS item GUID';

comment on column security_publications.publication_type is
  'Publication category: CPU, CSPU, or SECURITY_ALERT';

comment on column security_publications.advisory_url is
  'Official Oracle advisory URL taken from the RSS item link';

comment on column security_publications.published_on is
  'Official publication calendar date parsed from the RSS item pubDate';

comment on column security_publications.source_pub_date is
  'Original RSS pubDate value retained for change detection and traceability';

comment on column security_publications.alert_state is
  'Ingestion state: CURRENT for baseline items, NEW for new GUIDs, or UPDATED for changed items';

comment on column security_publications.first_seen_at is
  'Timestamp when the automation first discovered the publication';

comment on column security_publications.last_seen_at is
  'Timestamp when the automation most recently observed the publication in the feed';

comment on column security_publications.last_changed_at is
  'Timestamp when the stored RSS title, URL, or publication date last changed';

prompt Script 13 complete
